### PR TITLE
[refactor] Move util & swconfig from sw.sword into sw.golibs

### PR DESCRIPTION
**Pull request by JulienDERONGS**
* Move sw.sword//sword/config & sw.sword//util into sw.golibs/swconfig & sw.golibs/util
* Replace SWORD_VERSION by a parameter in util/log.Parse(...)
* Update README.md

### CODE REVIEW

**Comment by JulienDERONGS** [comment]
Goes in pair with https://github.com/masagroup/sw.sword/pull/8946

**Comment by lgylgy** [comment]
I don't understand this pr.
The goal of sw.golibs is to share common(and public) code between masagroup repositories.
What feature do you want to add in this repository?
For example, mapmerger is only used by sw.sword(admin), request for admin/slave/agents tests.
swconfig is 100% sw.sword dev tools. RedundantMsg/Checkpoint/PurgeTestDirs/... make no sense to be here.
PostJson with SID is only admin process.

There is a Jira ticket for this pr ?

**Comment by abrMasa** [comment]
@lgylgy:

The goal of this is to be able to use swapi in another repository (sw.nc1 in this case), to be able to instanciate timeline, simulation, etc for test purpose.

Since sw.sword is public, we cannot make sw.nc1 pull directly on github.com/masagroup/sw.sword to retrieve sw.swapi, so an incoming pr will package swapi in an archive so sw.nc1 can retrieve and use swapi code easily.

But swapi has dependencies on util and swconfig, so two possibilities:
1. we zip them as well as swapi
2. we move util and swconfig to sw.golibs

We have chosen option 2, but we are listenning if you have a better idea or good arguments for option 1.

P.S: you shouldn't work during you holidays ;)

**Comment by abrMasa** [comment]
it is for this story: https://masagroup.atlassian.net/browse/SW-6870

**Comment by lgylgy** [comment]
To use swapi, it's just a dependency problem(go package).
Remove 'util' and 'swconfig' from swapi. 99% of 'util' and swconfig are used by the sword tests.

Maybe the only things to move is 'util.Go'.

ps: I'm on a train, I have time to waste :). Upon my return, I will check this. Because now, it's not a clean solution.

**Comment by abrMasa** [comment]
Ok, we let it in standby, and we will discuss it on thursday when you'll be officially back in game :)

**Pull request closed without merging**
